### ISSUE TITLE
Setup Docsify in the project 

### ISSUE THREAD

**Issue by Swap76** [Swap76/ElasticSearch#1]
Setup Docsify in Project

If you are working on this then please comment here this will save other's work.

**Comment by Ania-chan** [comment]
Hi! Can I work on this issue? 😸

**Comment by Swap76** [comment]
Hey @Ania-chan, 

Start working on the issue I will assign the issue to you

**Comment by Ania-chan** [comment]
@Swap76 Thanks! I'll do it this week!

**Comment by Swap76** [comment]
Cool Please add the instructions in Readme file after done setting up Docsify
